### ISSUE TITLE
Linux serial port regression

### ISSUE THREAD

**Issue by tatokis** [thorpej/nabud#3]
Commit 6fc7139e2ef5a10176e415061838f2a9ca88ed1f broke the serial port on Linux again. Reverting it makes nabud work.

```
INFO: conn_add_serial: Creating Serial connection on /dev/ttyS0.
ERROR: conn_add_serial: cfsetspeed(NABU_NATIVE_BPS) on /dev/ttyS0 failed.
ERROR: conn_add_serial: cfsetspeed(NABU_FALLBACK_BPS) on /dev/ttyS0 failed.
ERROR: main: No connections! So boring! Goodbye.
```

Both `cfsetispeed(&t, NABU_FALLBACK_BPS)` and `cfsetospeed(&t, NABU_FALLBACK_BPS)` fail with EINVAL.

**Comment by thorpej** [comment]
Well poop.  Ok.

**Comment by thorpej** [comment]
Reverted in 227f4516cadd808569e85990f7afbf4965edd4f0.  Can you verify it works again?

Thanks!

**Comment by tatokis** [comment]
Yeah, it works again.
I've been manually reverting that commit.
